baseurl: "https://www.tilkov.com/"

title: "Stefan Tilkov"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"
languageCode: en-us

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

params:
  description: "Stefan Tilkov"
  footer: "&copy; 2020-2021 [Stefan Tilkov](/about) | [Home](/) | [RSS](/feed.atom) | [Twitter](https://twitter.com/stilkov)"
  mainSections: post

enableGitInfo: true


frontmatter:
  date:
    - :git

mediaTypes:
  application/atom+xml:
    suffixes:
    - atom

outputFormats:
  ATOM:
    name: ATOM
    baseName: feed
    mediaType: application/atom+xml


outputs:
  home:
  - HTML
  - ATOM
    
markup:
  goldmark:
    renderer:
      unsafe: true
