baseurl: "/"

title: "Stefan Tilkov"
googleAnalytics: ""
disqusShortname: ""
ignoreFiles: ["_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
footnotereturnlinkcontents: "↩"

permalinks:
  note: "/note/:year/:month/:day/:slug/"
  post: "/post/:year/:month/:day/:slug/"

params:
  description: "Stefan Tilkov"
  footer: "&copy; 2020-2021 [Stefan Tilkov](/about) | [Home](/) | [RSS](/index.xml) | [Twitter](https://twitter.com/stilkov)"

markup:
  goldmark:
    renderer:
      unsafe: true
